# Generated by Django 4.0.6 on 2022-07-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0005_category_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='categories', related_query_name='categories', to='shop_api.category'),
        ),
    ]
