# Generated by Django 4.0.6 on 2022-07-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_date',
            field=models.DateField(null=True),
        ),
    ]
