# Generated by Django 4.0.6 on 2022-07-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0010_product_image_productmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
