# Generated by Django 4.0.6 on 2022-07-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0012_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
